### ISSUE TITLE
data lost when updating to shopware 5.2 and using this plugin

### ISSUE THREAD

**Issue by lhwparis** [shopwareLabs/SwagAdditionalAttributes#1]
i use this plugin in my shop. now i did a test update to shopware 5.2RC3 and i saw all data stored in an additional field is lost and no more available. any solution to move dta over to the new attribute management in shopware 5.2?

**Comment by janbuecker** [comment]
Hi, I've tested the scenario with a fresh 5.1.6 installation. I've installed the plugin, added some data and updated to 5.2.0. After the update, the data is still present and the attributes show up in the attribute management.

Feel free to create a new issue with more information to reproduce.
